### ISSUE TITLE
Suggestion: default username for donations to domain names

### ISSUE THREAD

**Issue by AbelLykens** [andrerfneves/lightning-address#1]
Can we come up with a default reserved username for domain-donations?

For example, if you want to donate to `michaeljackson.com` for listening to some music, it knows to look up `https://michaeljackson.com/.well-known/lnurlp/info` ?

Having a standard would be good here I think. Having some reserved keywords from the start (info/webmaster/root/??) ensures implementations can consider these from the start.

**Comment by andrerfneves** [comment]
This is an interesting idea we hadn't thought of. I just wonder if we're overly complicating things because wallets would need to interpret full domains as try to fetch LNURL Pays from those. It's probably easier for the domain holder/provider to simply create donations@michaeljackson.com no?

**Comment by Fittiboy** [comment]
While I like the idea of this, reserved keywords are essentially impossible to enforce. For example, there are users on Twitter with the usernames webmaster, info, and donations.
Though I see a potential options for this:
`/.well-known/catchall/lnurlp` for a simple catchall. A GET request could be sent to this URL if no username is given (eg. sending to `example.org` instead of `user@example.org`).
Importantly, `catchall` comes *before* `lnurlp`, so as to not conflict with a user by that name.

**Comment by hsjoberg** [comment]
I'm not sure we should enforce this but I think it's likely that there will emerge a de-facto standard for this (probably donate@domain.com).

But some kind of catchall as @Fittiboy mentioned is something I've been trying to figure out as well.

**Comment by andrerfneves** [comment]
I actually think a catch all is counter productive. If I try to email an address that doesn't exist, it simply bounces back and doesnt work. If you have a catch all, now the client needs to make sure that the payload that's returned on the LNURL Pay is exactly for the user that you mean to send to. Not only that but it causes potential UX where you are trying to send to user@domain.com but that user doesn't exist, but you still receive a valid LNURL Pay that you can pay, and will successfully work. The user will think their payment was successful even though it was a safety catch all and the payment doesn't reach the desired party.

At most I think we can recommend the `donations@domain.com` as a safety that people are encouraged to provide/use but we simply cannot/should not enforce it.

**Comment by Fittiboy** [comment]
Catchall doesn‘t make sense for twitter.com, but nobody besides the domain owner will receive at something like a personal blog‘s URL either way.
But then again, catchalls are easy to set up as is, like I already do at literally_any_valid_username_here@fitti.io for example.
A `/.well-known/lnurlp/.catchall` endoint or something would enable sending to `example.org` without a username though.

**Comment by andrerfneves** [comment]
I don't think we should allow for the case where a lightning address doesnt have a username (aka an actual URL). Makes it more complex for clients to implement and then its no longer an internet identifier but a URL, causing confusion for users as well I think.

**Comment by Fittiboy** [comment]
I personally like the idea of sending to a URL without adding a username. But I agree that it just adds complexity for little reward.

**Comment by andrerfneves** [comment]
Closing this thread for now.
