### ISSUE TITLE
will you support Sats Names?

### ISSUE THREAD

**Issue by ghost** [andrerfneves/lightning-address#100]
Sats Names is a standard for writing names to Bitcoin using ordinals. The goal is to build a name ecosystem for Bitcoin, that is built by Bitcoiners, and developed entirely on Bitcoin.

https://docs.sats.id/

**Comment by mumu2023** [comment]
as we all know, now the lightning-address is not decentralized，may be Sats Names can be a better way for lightning-address

**Comment by 88rirjror** [comment]
VRO

**Comment by andrerfneves** [comment]
Duplicate issue

**Comment by andrerfneves** [comment]
ref https://github.com/andrerfneves/lightning-address/issues/104
