### ISSUE TITLE
Suggestion: optional index

### ISSUE THREAD

**Issue by AbelLykens** [andrerfneves/lightning-address#2]
Suggestion:
Add reserved keyword `index`, where users can *optionally* put a plaintext list of usernames, within `/.well-known/lnurlp/index`

**Comment by AbelLykens** [comment]
I accidentally added this to PR #4

**Comment by andrerfneves** [comment]
What is the reason for having a list of usernames available on `index`? Isn't this a bit of a privacy leak?

**Comment by AbelLykens** [comment]
`rollingstones.com/.well-known/lnurlp/index` could show:

```
Mick
Keith
Charlie
Ron
```

It for sure has to be optional, but I see reasons this can be used. 

Possibly for podcasts (coolpodcast.com), it could show all hosts?

**Comment by andrerfneves** [comment]
@fiajaf @Fittiboy @hampus what do we think of an optional INDEX file? I think it could be helpful but only for very specific cases. Could be part of OPTIONAL spec

**Comment by hsjoberg** [comment]
I'm not seeing any immediate use-case for this really, but I might just be ignorant. Donation addresses for the Rolling Stones could just be provided from the site in question.

Anyway it sounds like a simple thing and doesn't really hurt to add.
I would suggest to use `.index` instead of `index` though to mitigate any potential collision with a username index.
Also dot syntax or something similar should probably used for other possible extensions.

**Comment by Fittiboy** [comment]
OPTIONAL + dot syntax sounds good to me.
Site run by two podcasters and one has a difficult name? Just check /.index real quick. I like the idea.

**Comment by andrerfneves** [comment]
"Check .index real quick" assumes a person/user would be manually doing that. We need to think of the actual user flows. What is the case where that API would actually be fetched? Explain how and why a wallet or app would show this UX flow and why exactly? I dont think this is actually as useful.

**Comment by Fittiboy** [comment]
Hmm, maybe a user manually types .index@domain.com? Or when a user types a wrong username, and the site doesn‘t return an lnurl-pay link, the wallet offers to check .index?

**Comment by Fittiboy** [comment]
Thinking about it more: When it's optional, I don't see any wallets implementing this. And it obviously has to be optional.
I don't think it's worth the added complexity.

**Comment by andrerfneves** [comment]
Agreed

**Comment by andrerfneves** [comment]
Closing this for now.
