### ISSUE TITLE
Should the list of Wallets Supported include only Apps, or LN wallets from websites as well?

### ISSUE THREAD

**Issue by cointastical** [andrerfneves/lightning-address#34]
It looks like some sites where the user has a LN wallet are now also adding Lightning Address support.  For example. every account nym on Stacker.News gets a corresponding Lightning Address (e.g., <nym>@Stacker.News ).

Would these get added to the list of [Wallets Supported](https://github.com/andrerfneves/lightning-address/blob/master/README.md#wallets-supported)?

Or should websites providing Lighting Address support for their users be a separate list from the existing list which consists of LN Wallet apps (e.g., BlueWallet) and LN wallet services (e.g., @LNTxBot on Telegram)?

Now that I think about it, this might not just apply to websites with Lightning Addresses for their users.  Let's say some mobile gaming app uses LN and each player gets a Lightning Address, ... kind of would be the same issue.

**Comment by cointastical** [comment]
Looks like these are reference to #services on fiatjaf's lnurl repo:  

*Services*
https://github.com/fiatjaf/lnurl-rfc#services

**Comment by andrerfneves** [comment]
Yeah this is definitely a place where we can improve the separation here. Services !== Wallets, I agree with you.

I could see possibly see refactoring things to relate this change, but the distinction becomes blurred very quickly. Services with Wallets have almost (if not all) of the functionality of Wallets. Some Services even have mobile apps which allow for the same capabilities. 

Maybe we need a broader term: `Products and Services supporting Lightning Addresses` and change the UI of it a bit? Not sure how to proceed tbh

**Comment by andrerfneves** [comment]
PRs are welcome. Going to close this for now.
