### ISSUE TITLE
HNS compatiblity

### ISSUE THREAD

**Issue by miguelgargallo** [andrerfneves/lightning-address#45]
Good morning,
Is there a way, to make this compatible with HNS Blockchain technology and their TLDs and SLDs?

**Comment by hugomd** [comment]
@miguelgargallo there's nothing stopping lightning addresses being used with HNS domains, provided the caller can resolve them via DNS.

**Comment by miguelgargallo** [comment]
So! I will implement this into [https://github.com/itamaeasan/sushijs](ITAMAESAN/SushiJS)  framework in a while! Thanks bro!

**Comment by andrerfneves** [comment]
👍
