### ISSUE TITLE
Suggestion: Offer support

### ISSUE THREAD

**Issue by AaronDewes** [andrerfneves/lightning-address#46]
Having some kind of bolt12 offer support for lightning addresses would probably make lightning addresses easier to set up and use.

They would mean fewer requests (it's simple to create an any amount bolt12 offer, so the bolt12 can be sent with the initial request), allow hosting a lightning address on a static web hosting provider (like GitHub pages), and could potentially also be cached locally.

This could be implemented by extending the current spec by adding an additional key `bolt12` to the initial reply from `. well-known/lnurlp/name`. If it's present, this bolt12 offer will be used, otherwise the normal LNUrl flow will be used.

**Comment by andrerfneves** [comment]
That part of the spec is actually the LUD06 specification: https://github.com/fiatjaf/lnurl-rfc/blob/luds/06.md

**Comment by andrerfneves** [comment]
Closing this since this discussion is with regards to the underlying LNURL Pay spec and not Lightning Address itself. Let's reopen this conversation on the proper LNURL repository
