### ISSUE TITLE
Suggestion: Higher Transferlimit

### ISSUE THREAD

**Issue by jln325** [andrerfneves/lightning-address#47]
Hello

This is my first post in Github. I hope I do it correctly.
Is it possible to integrate a way how I can increase the transfer limit?
Iam using bridge server for lightning addresses.
Currently only 0.001 Bitcoin is possible. A higher limit such as e.g. 0.1 or 0.01 btc to receive the bitcoin via the email address would of course be great.

Thank you for your review

**Comment by andrerfneves** [comment]
The Lightning Address protocol doesn't specify any transfer limits of any kind. You may be referring to the `maxSendable` and `minSendable` properties of the LNURL Pay response from LUD 06 (https://github.com/fiatjaf/lnurl-rfc/blob/luds/06.md). Those are handled by your backend provider. If you're using a 3rd party provider or bridge then they are the ones setting that amount.
