### ISSUE TITLE
Signet test wallet(s)?

### ISSUE THREAD

**Issue by Sjors** [andrerfneves/lightning-address#48]
Are there any wallets that implement sending to a lightning address and that work with Signet? I already stalked two projects: https://github.com/BlueWallet/BlueWallet/issues/4724 / https://github.com/ACINQ/phoenix/issues/270

**Comment by andrerfneves** [comment]
I haven't heard of one that supports signet myself

**Comment by ok300** [comment]
Check out [Plebnet Playground](https://github.com/PLEBNET-PLAYGROUND/plebnet-playground-docker):

> This package will setup a bitcoind, lnd, and tor daemon that will connect to the Plebnet Playground Sandbox (Signet) Chain. This allows users to use and test bitcoin and lightning technologies without the financial risk involved with running on the mainnet chain. RTL (Ride The Lightning) and ThunderHub Web UI is also include to provide a more user friendly experience.

AFAIK ThunderHub supports sending to LN Address.

**Comment by ok300** [comment]
Another (maybe faster) approach: you could setup Citadel in a VM, it has support for signet (runcitadel/core#15). Then from their appstore get ThunderHub for sending to LN Addresses.

**Comment by andrerfneves** [comment]
Few options provided above. Going to go ahead and close this. 👍
