### ISSUE TITLE
image has typo

### ISSUE THREAD

**Issue by pseudozach** [andrerfneves/lightning-address#6]
It says TDLR, it should be TLDR I think. just a small annoyance.
https://camo.githubusercontent.com/836ed364aec65d81d0bfb8a85f20a151e4488e0404ab79a0b30b88b88831a6ba/68747470733a2f2f692e696d6775722e636f6d2f346167697662482e706e67

**Comment by andrerfneves** [comment]
I hate that I didn't catch this one. Ugh
I'll fix it

**Comment by andrerfneves** [comment]
Resolved here https://github.com/andrerfneves/lightning-address/commit/a19b454ce69678580339f18b5279b3ee10b23337
