### ISSUE TITLE
Unsupported character in website and extension

### ISSUE THREAD

**Issue by jamescridland** [andrerfneves/lightning-address#63]
![Screen Shot 2022-07-17 at 9 51 09 pm](https://user-images.githubusercontent.com/231941/179396886-6b06b241-29f5-4be7-8291-bd7135a14650.png)

Above - I guess the character at the end of my Alby name is supposed to mean something, but on this Mac (using Chrome), it appears to be just an unrecognised Unicode character.

**Comment by andrerfneves** [comment]
This should be raised on the Alby team's repositories https://github.com/getAlby
