### ISSUE TITLE
Change your LNURL endpoint

### ISSUE THREAD

**Issue by EZ0010** [andrerfneves/lightning-address#9]
Hi, I live in a country where zebedee . io isn't supported, and they don't just don't support it they even block all requests from my ip to their endpoint when I try to send anything to your LNURL so I can't send a donation to your LNURL. please consider changing it.
Thanks.

![photo_2021-08-15 17 04 13](https://user-images.githubusercontent.com/75021359/129481168-3bd4919a-1890-4d44-a686-530549467aa8.jpeg)

**Comment by andrerfneves** [comment]
This is a Lightning Address repository, not related to ZEBEDEE. I can however tell you that ZEBEDEE is working hard to open up all regions as soon as possible.

**Comment by EZ0010** [comment]
thanks for reply but sorry, this issue IS related to this reposidtory and not ZEBEDEE, you have the donation address in the README.md file and I can't donate to it, as I titled this issue please change the address I didn't say fix ZEBEDEE.

also good to mention that Bitcoin SHOULD be censorship resistance. please keep that in mind.

**Comment by andrerfneves** [comment]
I've added a new one.
